id: AA0433F6F
base_file: f4C48.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:57:06.997330
  last_modified_at: 2022-05-30 20:57:06.997333
