id: AA0433F6F
base_file: f9D5D.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:57:07.004723
  last_modified_at: 2022-05-30 20:57:07.004726
