id: AA0433F6F
base_file: f4ED6.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:57:07.000795
  last_modified_at: 2022-05-30 20:57:07.000798
